import 'package:freezed_annotation/freezed_annotation.dart';
import 'order_status.dart';

part 'order.freezed.dart';
part 'order.g.dart';

/// Order wrapper - combines public status with encrypted details
/// Public status can use kind 30078 (custom) or track via DM thread
@freezed
class Order with _$Order {
  const factory Order({
    required String id, // order ID generated by customer
    required String customerPubkey, // customer's public key
    required String merchantPubkey, // merchant's public key
    required OrderStatus status, // current order status
    required DateTime createdAt,
    DateTime? updatedAt,
    
    // Optional fields for tracking
    String? stallId, // which stall this order is for
    String? stallName, // cached stall name
    DateTime? estimatedReady, // when order will be ready
    String? riderPubkey, // assigned rider if any
    
    // Event references
    String? statusEventId, // public status event ID
    String? detailsEventId, // encrypted details event ID (kind 4)
    
    // Decrypted order details (loaded separately via NIP-04/NIP-44)
    OrderDetails? details,
  }) = _Order;

  factory Order.fromJson(Map<String, dynamic> json) => _$OrderFromJson(json);
}

/// NIP-15 Customer Order (Type 0)
/// Sent as encrypted JSON in kind 4 event content
@freezed
class OrderDetails with _$OrderDetails {
  const factory OrderDetails({
    required String id, // order ID (same as Order.id)
    @Default(0) int type, // message type: 0 = new order
    String? name, // customer name (optional)
    String? address, // physical address for goods (optional)
    String? message, // message for merchant (optional)
    required ContactInfo contact, // customer contact information
    required List<OrderItem> items, // products being ordered
    required String shippingId, // selected shipping zone ID
    
    // Additional fields for payment tracking
    String? paymentHash, // Lightning payment hash
    String? paymentPreimage, // Payment proof
    int? total, // total amount in smallest unit
    int? subtotal, // items subtotal
    int? shippingCost, // shipping cost
    int? discount, // any discounts applied
  }) = _OrderDetails;

  factory OrderDetails.fromJson(Map<String, dynamic> json) =>
      _$OrderDetailsFromJson(json);
}

/// NIP-15 Contact Information
/// Customer contact details for order follow-up
@freezed
class ContactInfo with _$ContactInfo {
  const factory ContactInfo({
    required String nostr, // 32-bytes hex pubkey (required in spec)
    String? phone, // phone number if customer wants phone contact
    String? email, // email if customer wants email contact
  }) = _ContactInfo;

  factory ContactInfo.fromJson(Map<String, dynamic> json) =>
      _$ContactInfoFromJson(json);
}

/// Order Item
/// Individual product in an order
@freezed
class OrderItem with _$OrderItem {
  const factory OrderItem({
    required String productId, // reference to product
    required int quantity, // how many units
    
    // Cached for display (not in NIP-15 spec but useful)
    String? productName,
    double? price, // price per unit
    Map<String, dynamic>? customization, // product customization
    String? notes, // special instructions for this item
  }) = _OrderItem;

  factory OrderItem.fromJson(Map<String, dynamic> json) =>
      _$OrderItemFromJson(json);
}

/// NIP-15 Payment Request (Type 1)
/// Merchant's response with payment options
@freezed
class PaymentRequest with _$PaymentRequest {
  const factory PaymentRequest({
    required String id, // order ID
    @Default(1) int type, // message type: 1 = payment request
    String? message, // message to customer (optional)
    @Default([]) List<PaymentOption> paymentOptions, // available payment methods
  }) = _PaymentRequest;

  factory PaymentRequest.fromJson(Map<String, dynamic> json) =>
      _$PaymentRequestFromJson(json);
}

/// Payment Option
/// Different payment methods available
@freezed
class PaymentOption with _$PaymentOption {
  const factory PaymentOption({
    required String type, // url, btc, ln, lnurl
    required String link, // payment URL, address, invoice, etc.
  }) = _PaymentOption;

  factory PaymentOption.fromJson(Map<String, dynamic> json) =>
      _$PaymentOptionFromJson(json);
}

/// NIP-15 Order Status Update (Type 2)
/// Merchant confirms payment and shipping status
@freezed
class OrderStatusUpdate with _$OrderStatusUpdate {
  const factory OrderStatusUpdate({
    required String id, // order ID
    @Default(2) int type, // message type: 2 = status update
    String? message, // message to customer
    required bool paid, // has received payment
    required bool shipped, // has been shipped
  }) = _OrderStatusUpdate;

  factory OrderStatusUpdate.fromJson(Map<String, dynamic> json) =>
      _$OrderStatusUpdateFromJson(json);
}

// Legacy - keeping for backwards compatibility
@freezed
class DeliveryAddress with _$DeliveryAddress {
  const factory DeliveryAddress({
    required String street,
    required String city,
    String? district,
    String? postcode,
    String? country,
    double? lat,
    double? lon,
    String? notes,
  }) = _DeliveryAddress;

  factory DeliveryAddress.fromJson(Map<String, dynamic> json) =>
      _$DeliveryAddressFromJson(json);
}
