import 'package:freezed_annotation/freezed_annotation.dart';
import 'stall_type.dart';

part 'stall.freezed.dart';
part 'stall.g.dart';

/// NIP-15 Stall Model (kind 30017)
/// Base implementation following NIP-15 spec with food delivery extensions
@freezed
class Stall with _$Stall {
  const factory Stall({
    // NIP-15 Core Fields
    required String id, // d tag - merchant generated ID
    required String name, // stall name
    String? description, // stall description (optional per NIP-15)
    required String currency, // currency used (BTC, USD, THB, etc.)
    @Default([]) List<ShippingZone> shipping, // NIP-15 shipping zones
    
    // Food Delivery Extensions (stored as tags or in description)
    StallType? stallType, // food or shop (custom extension)
    String? cuisine, // for food stalls (thai, italian, japanese, etc.)
    @Default(true) bool acceptsOrders, // whether accepting orders
    int? preparationTime, // average preparation time in minutes
    String? operatingHours, // "09:00-22:00"
    String? locationEncrypted, // NIP-44 encrypted address for merchant
  double? latitude,
  double? longitude,
  String? locationName,
    
    // Metadata (not in event content, derived from event)
    String? eventId,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) = _Stall;

  factory Stall.fromJson(Map<String, dynamic> json) => _$StallFromJson(json);

  // Helper for creating empty stall
  factory Stall.empty({StallType? stallType}) {
    return Stall(
      id: DateTime.now().millisecondsSinceEpoch.toString(),
      name: '',
      currency: 'BTC',
      stallType: stallType,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    );
  }
}

/// NIP-15 Shipping Zone Model
/// Represents different shipping zones with costs and regions
@freezed
class ShippingZone with _$ShippingZone {
  const factory ShippingZone({
    required String id, // zone ID generated by merchant
    String? name, // zone name (optional)
    required double cost, // base shipping cost in stall currency
    @Default([]) List<String> regions, // regions included in this zone
  }) = _ShippingZone;

  factory ShippingZone.fromJson(Map<String, dynamic> json) =>
      _$ShippingZoneFromJson(json);
}
